version: '3'
services:
  web:
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    environment:
      - ADMIN_USER
      - ADMIN_PASSWORD
      - RAILS_ENV=development
      - REDIS_HOST=redis
    ports:
      - 3000:3000
    depends_on:
      - redis
  redis:
    image: redis:latest
  
volumes:
  redis:
  

